# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 18:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0002_auto_20170516_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vahay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vahay.Vahay'),
            preserve_default=False,
        ),
    ]
