# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0002_worldborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahay',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
