# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0003_review_vahay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vahay',
            old_name='rating',
            new_name='vote',
        ),
    ]
