# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0003_vahay_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vahay',
            name='address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
