# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0004_auto_20170530_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vahay',
            name='description',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
    ]
