# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0005_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_link',
            new_name='link',
        ),
    ]
