# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-20 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vahay', '0006_auto_20170519_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='vahay',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
